### ISSUE TITLE
What should the --lr-params be?

### ISSUE THREAD

**Issue by SE-Nickjackson** [csiro-robotics/iSICE#1]
Thanks a lot for your great wok! 
But when I run the command 'python main.py data/ --benchmark dataset  --epochs 100 --lr 1.2e-4 --lr-method step --lr-params 15\ 30 -j 10 -b 65 --num-classes 200 --representation SICE --freezed-layer 0 --classifier-factor 5 --modeldir checkpoints/', I get error message: 'main.py: error: argument --lr-params: invalid float value: '15\\''

**Comment by saimunur** [comment]
Hi @SE-Nickjackson, thanks for finding this issue. I have just updated the repository with some potential known issues. Please download the updated repository with the latest instructions. Thanks.
